# Test Makefile

hellorun: helloworld.cpp
	g++ -o ./build/helloworld helloworld.cpp
	./build/helloworld

ifrun: if.cpp
	g++ -o ./build/if if.cpp
	./build/if

ifelserun: ifelse.cpp
	g++ -o ./build/ifelse ifelse.cpp
	./build/ifelse

whilerun: while.cpp
	g++ -o ./build/while while.cpp
	./build/while

forrun: for.cpp
	g++ -o ./build/for for.cpp
	./build/for
	
arrayrun: array.cpp
	g++ -o ./build/array array.cpp
	./build/array

switchrun: switch.cpp
	g++ -o ./build/switch switch.cpp
	./build/switch

headerrun: header.cpp
	g++ -o ./build/header header.cpp
	./build/header

classesrun: classes.cpp
	g++ -o ./build/classes classes.cpp cat.cpp
	./build/classes

ssrun: stringstreams.cpp
	g++ -o ./build/stringstreams stringstreams.cpp
	./build/stringstreams

pointersrun: pointers.cpp
	g++ -o ./build/pointers pointers.cpp
	./build/pointers

mathrun: arithmetic.cpp
	g++ -o ./build/arithmetic arithmetic.cpp
	./build/arithmetic

chararrayrun: chararray.cpp
	g++ -o ./build/chararray chararray.cpp
	./build/chararray

referencesrun: references.cpp
	g++ -o ./build/references references.cpp
	./build/references

construn: const.cpp
	g++ -o ./build/const const.cpp
	./build/const

copyrun: copyconstructors.cpp
	g++ -o ./build/copyconstructors copyconstructors.cpp
	./build/copyconstructors

memoryrun: memory.cpp
	g++ -o ./build/memory memory.cpp
	./build/memory

arrayfuncrun: arrayfunc.cpp
	g++ -o ./build/arrayfunc arrayfunc.cpp
	./build/arrayfunc

namespacesrun: namespaces.cpp
	g++ -o ./build/namespaces namespaces.cpp lights.cpp lamp.cpp
	./build/namespaces