# Test Makefile

hello: helloworld.cpp
	g++ -o helloworld helloworld.cpp

hellorun: helloworld.cpp
	g++ -o helloworld helloworld.cpp
	./helloworld

ifrun: if.cpp
	g++ -o if if.cpp
	./if

ifelserun: ifelse.cpp
	g++ -o ./build/ifelse ifelse.cpp
	./build/ifelse