# Test Makefile

inheritancerun: inheritance.cpp
	g++ -o ./build/inheritance inheritance.cpp
	./build/inheritance

pointerrun: pointer.cpp
	g++ -o ./build/pointer pointer.cpp
	./build/pointer

copyconstrrun: copyconstr.cpp
	g++ -o ./build/copyconstr copyconstr.cpp
	./build/copyconstr
